name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/Spotify_Downloader
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          docker stop spotify-downloader || true
          docker rm spotify-downloader || true
          docker build -t spotify-downloader .
          docker run -d --name spotify-downloader -p 5000:5000 spotify-downloader
